# Generated by Django 4.1.6 on 2023-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRestaurante', models.CharField(max_length=200)),
                ('identificacionUsuario', models.CharField(max_length=200)),
                ('menu', models.CharField(max_length=200)),
                ('valorMenu', models.IntegerField()),
                ('fechaPago', models.CharField(max_length=200)),
                ('valorPagado', models.IntegerField()),
            ],
        ),
    ]
