# Generated by Django 4.1.6 on 2023-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fechaPago',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
